package sources

var Steps = map[string]string{
	"enter_email":    	"#i0116",
	"next_password":  	"#idSIButton9",
	"enter_password": 	"#i0118",
	"sign_in":        	"#idSIButton9",
	"cancel":         	"#cancelLink",
	//"ch-vid":				`.lesson-menu-activities-list:nth-child(1)>a`,
	"B2" :			  `ol.level-filters-bar-list > li:nth-child(5)> button`,
	"01-choice":		`ul.mission-lessons-list li:first-child a[data-test="lesson-link"]`,
	"ch1-vid": 			`ul.lesson-menu-activities-list li:nth-child(1) a[data-test="activity-VIDEO-link"]`,
	"ch2-syn": 			`ul.lesson-menu-activities-list li:nth-child(2) a[data-tes~t="activity-VOCABULARY_LIST-link"]`,
	"ch2-exs1":			`ul.lesson-menu-activities-list li:nth-child(3) a[data-test="activity-EXERCISE-link"]`,
	"continue":			`div.footer-button-bar-row button[data-test="footer-bar-button"]`,
	"move_on":			`main > altissia-activity-result > div > div.result-button-box > altissia-main-button button[data-test="main-button"]`,

	"lesson-card":		`a.new-card.lesson-card-container.lesson-card-container-is-active[data-test="lesson-link"]`,
	"B2-button":     	`button.level-filter-btn.level-filter-btn-is-active[data-test="level-filter-button"]`,
	"other_account": 	"#otherTileText",
	"choose-video" :		`a.new-card.activity-overview-card.activity-overview-card-is-active[data-test="activity-VIDEO-link"]`,
	"next":          	"#idSIButton9",
	"submit_again":  	"#idSIButton9",
	"yes":           	"#idSIButton9",
	"select_lesson": 	".lesson-card-container-is-active > div:nth-child(1)",
	"select_video":  	".lesson-menu-activities-list > li:nth-child(1) > altissia-activity-overview-card:nth-child(1) > a:nth-child(1)",
	"video_element": 	".media-player-container",
	"mute":          	"#app-main-content > altissia-app-container > div > main > altissia-app-video-activity > div > div > altissia-media-player > div > div > plyr > div > div.plyr__controls > div.plyr__controls__item.plyr__volume > button",
	"video_id":      	".plyr__video-wrapper > video:nth-child(1)",
	"play_btn":      	"button.plyr__controls__item:nth-child(1)",
	"video_dur":     	"div.plyr__controls__item:nth-child(3)",
	"after-video":		`button[data-test="main-button"]`,
	//"continue":      	".center-content",
}
